width: 512
height: 512

affines:
 - [1.005, 0.0, 0.0, 0.0, 1.005, 0.0, 0.498, 0.0, 1.0]
 - [0.0, 1.005, 0.0, 0.0, 0.0, 1.005, 0.498, 0.0, 1.0]
 - [-0.995, 1.002, 0.0, -1.002, 0.995, 0.0, 1.0, 0.4, 0.698]

variations:
 - Linear
 - Sinusoidal
 - Spherical
 - Swirl
 - Horseshoe

samples: 4096
iter-per-sample: 8192

seed: 2

symmetry: 16
is-relative-symmetry: false

number-of-threads: 4
